<a href="https://colab.research.google.com/github/gmurari30/gmurari30/blob/main/ML_Cup_event3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML Cup Event #3

In [1]:
import pandas as pd
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import sklearn
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The scikit-learn version is 0.22.2.post1.


In [ ]:
import os
os.getcwd()

"C:\\Users\\st50\\OneDrive - Queen's University\\Courses\\202010_MMA869\\ML Cup\\Event4"

In [4]:
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("diabetes_train.csv")

Id_col = 'Id'
target_col = 'diabetes'
df.info()
df.head()

Saving diabetes_train.csv to diabetes_train.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Id                  576 non-null    int64  
 1   num_times_pregnant  576 non-null    int64  
 2   plasma_glucose      576 non-null    int64  
 3   DBP                 576 non-null    int64  
 4   triceps_skin        576 non-null    int64  
 5   serum_insulin       576 non-null    int64  
 6   BMI                 576 non-null    float64
 7   pedigree            576 non-null    float64
 8   age                 576 non-null    int64  
 9   diabetes            576 non-null    int64  
dtypes: float64(2), int64(8)
memory usage: 45.1 KB


Id  num_times_pregnant  plasma_glucose  DBP  ...   BMI  pedigree  age  diabetes
0  358                  13             129    0  ...  39.9     0.569   44         1
1   74                   4             129   86  ...  35.1     0.231   23         0
2  353                   3              61   82  ...  34.4     0.243   46         0
3  498                   2              81   72  ...  30.1     0.547   25         0
4  146                   0             102   75  ...   0.0     0.572   21         0

[5 rows x 10 columns]

In [5]:
from sklearn.model_selection import train_test_split

X = df.drop([Id_col, target_col], axis=1)
y = df[target_col]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
X.info()
X.shape
X.head()

X_train.info()
X_train.shape
X_train.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   num_times_pregnant  576 non-null    int64  
 1   plasma_glucose      576 non-null    int64  
 2   DBP                 576 non-null    int64  
 3   triceps_skin        576 non-null    int64  
 4   serum_insulin       576 non-null    int64  
 5   BMI                 576 non-null    float64
 6   pedigree            576 non-null    float64
 7   age                 576 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 36.1 KB


(576, 8)

num_times_pregnant  plasma_glucose  DBP  ...   BMI  pedigree  age
0                  13             129    0  ...  39.9     0.569   44
1                   4             129   86  ...  35.1     0.231   23
2                   3              61   82  ...  34.4     0.243   46
3                   2              81   72  ...  30.1     0.547   25
4                   0             102   75  ...   0.0     0.572   21

[5 rows x 8 columns]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 460 entries, 437 to 102
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   num_times_pregnant  460 non-null    int64  
 1   plasma_glucose      460 non-null    int64  
 2   DBP                 460 non-null    int64  
 3   triceps_skin        460 non-null    int64  
 4   serum_insulin       460 non-null    int64  
 5   BMI                 460 non-null    float64
 6   pedigree            460 non-null    float64
 7   age                 460 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 32.3 KB


(460, 8)

num_times_pregnant  plasma_glucose  DBP  ...   BMI  pedigree  age
437                   6             102   82  ...  30.8     0.180   36
63                    7             142   60  ...  28.8     0.687   61
208                   1             119   44  ...  35.5     0.280   25
60                    8             143   66  ...  34.9     0.129   41
15                    0             123   88  ...  35.2     0.197   29

[5 rows x 8 columns]

In [7]:
np.bincount(y)

array([377, 199])

# Build Model

Gradient Boosting Classifier

In [22]:
#check the performance for different learning rates
lr_list = [0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1]

for learning_rate in lr_list:
    clf1 = GradientBoostingClassifier(n_estimators=20, learning_rate=learning_rate, max_features=2, max_depth=2, random_state=0)
    clf1.fit(X_train, y_train)

    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(clf1.score(X_train, y_train)))
    print("Accuracy score (validation): {0:.3f}".format(clf1.score(X_val, y_val)))

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.05, loss='deviance', max_depth=2,
                           max_features=2, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=20,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

Learning rate:  0.05
Accuracy score (training): 0.774
Accuracy score (validation): 0.819


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.075, loss='deviance', max_depth=2,
                           max_features=2, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=20,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

Learning rate:  0.075
Accuracy score (training): 0.787
Accuracy score (validation): 0.819


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=2,
                           max_features=2, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=20,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

Learning rate:  0.1
Accuracy score (training): 0.791
Accuracy score (validation): 0.819


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.25, loss='deviance', max_depth=2,
                           max_features=2, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=20,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

Learning rate:  0.25
Accuracy score (training): 0.824
Accuracy score (validation): 0.810


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.5, loss='deviance', max_depth=2,
                           max_features=2, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=20,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

Learning rate:  0.5
Accuracy score (training): 0.852
Accuracy score (validation): 0.784


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.75, loss='deviance', max_depth=2,
                           max_features=2, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=20,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

Learning rate:  0.75
Accuracy score (training): 0.880
Accuracy score (validation): 0.793


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=1, loss='deviance', max_depth=2,
                           max_features=2, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=20,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

Learning rate:  1
Accuracy score (training): 0.887
Accuracy score (validation): 0.793


In [23]:
from sklearn.ensemble import GradientBoostingClassifier

clf1 = GradientBoostingClassifier(max_depth=2)
clf1.fit(X_train, y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=2,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [24]:
#Gradient Boosting model performance
from sklearn.metrics import confusion_matrix

pred_val = clf1.predict(X_val)
pred_val

confusion_matrix(y_val, pred_val)

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1])

array([[72,  9],
       [15, 20]])

In [25]:
from sklearn.metrics import classification_report

print(classification_report(y_val, pred_val))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86        81
           1       0.69      0.57      0.62        35

    accuracy                           0.79       116
   macro avg       0.76      0.73      0.74       116
weighted avg       0.79      0.79      0.79       116



Random Forest Classifier

In [26]:
from sklearn.ensemble import RandomForestClassifier

clf2 = RandomForestClassifier(max_depth=2)
clf2.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [27]:
#Random Forest model performance
from sklearn.metrics import confusion_matrix

pred_val = clf2.predict(X_val)
pred_val

confusion_matrix(y_val, pred_val)

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0])

array([[80,  1],
       [20, 15]])

In [28]:
from sklearn.metrics import classification_report

print(classification_report(y_val, pred_val))

              precision    recall  f1-score   support

           0       0.80      0.99      0.88        81
           1       0.94      0.43      0.59        35

    accuracy                           0.82       116
   macro avg       0.87      0.71      0.74       116
weighted avg       0.84      0.82      0.79       116



Extra Tree Classifier

In [88]:
from sklearn.tree import ExtraTreeClassifier

clf3 = ExtraTreeClassifier(max_depth=2, min_samples_leaf=10)
clf3.fit(X_train, y_train)

ExtraTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                    max_depth=2, max_features='auto', max_leaf_nodes=None,
                    min_impurity_decrease=0.0, min_impurity_split=None,
                    min_samples_leaf=10, min_samples_split=2,
                    min_weight_fraction_leaf=0.0, random_state=None,
                    splitter='random')

In [89]:
#Extra Tree Model performance
from sklearn.metrics import confusion_matrix

pred_val = clf3.predict(X_val)
pred_val

confusion_matrix(y_val, pred_val)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0])

array([[74,  7],
       [22, 13]])

In [90]:
from sklearn.metrics import classification_report

print(classification_report(y_val, pred_val))

              precision    recall  f1-score   support

           0       0.77      0.91      0.84        81
           1       0.65      0.37      0.47        35

    accuracy                           0.75       116
   macro avg       0.71      0.64      0.65       116
weighted avg       0.73      0.75      0.73       116



XGBoost Classifier

In [120]:
from xgboost import XGBClassifier

clf4 = XGBClassifier(max_depth=2, learning_rate=0.05)
clf4.fit(X_train, y_train)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.05, max_delta_step=0, max_depth=2,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [121]:
#XGBoost Model performance
from sklearn.metrics import confusion_matrix

pred_val = clf4.predict(X_val)
pred_val

confusion_matrix(y_val, pred_val)

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0])

array([[74,  7],
       [16, 19]])

In [122]:
from sklearn.metrics import classification_report

print(classification_report(y_val, pred_val))

              precision    recall  f1-score   support

           0       0.82      0.91      0.87        81
           1       0.73      0.54      0.62        35

    accuracy                           0.80       116
   macro avg       0.78      0.73      0.74       116
weighted avg       0.79      0.80      0.79       116



Decision Tree Classifier

In [105]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(max_depth=2, criterion='gini', min_samples_leaf=30)
clf.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=2, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=30, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [106]:
#Decision Tree model performance
from sklearn.metrics import confusion_matrix

pred_val = clf.predict(X_val)
pred_val

confusion_matrix(y_val, pred_val)

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

array([[78,  3],
       [19, 16]])

In [107]:
from sklearn.metrics import classification_report

print(classification_report(y_val, pred_val))

              precision    recall  f1-score   support

           0       0.80      0.96      0.88        81
           1       0.84      0.46      0.59        35

    accuracy                           0.81       116
   macro avg       0.82      0.71      0.73       116
weighted avg       0.82      0.81      0.79       116



# Create Submission File on Test Data

In [123]:
#import the test dataset
from google.colab import files
uploaded = files.upload()

test_df = pd.read_csv('diabetes_test.csv')


Saving diabetes_test.csv to diabetes_test (4).csv


In [124]:

# Make sure to transform/create the features the same way you did for training
# For now, nothing to do

X_test = test_df.drop([Id_col], axis=1)

In [125]:

# Use your model to make predictions
pred_test = clf4.predict(X_test)

# We will look at the predicted prices to ensure we have something sensible.
print(pred_test)

[0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 1 1 1 1 1 1
 1 0 1 0 0 1 0 0 1 1 0 0 1 0 1 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 1 0
 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1
 0 0 0 1 1 0 0]


In [126]:

#submission format

my_submission = pd.DataFrame({'Id': test_df.Id, 'Predicted': pred_test})

my_submission.head()

# you could use any filename. We choose submission here
my_submission.to_csv('my_submission_XG.csv', index=False)

Id  Predicted
0  669          0
1  325          0
2  625          0
3  691          0
4  474          0

In [127]:
#download the submission file from colab
from google.colab import files
files.download('my_submission_XG.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>